version: "3"
services:
  api:
    build:
      context: ./api
    container_name: api
    environment:
      - PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - postgres
    command: npm run start:dev
  ###################
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
    env_file:
      - .env
  ################
  front:
    build:
      context: ./front
    container_name: front
    environment:
      - REACT_APP_API_URL=localhost:${API_PORT}
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    volumes:
      - ./front:/usr/src/app
    depends_on:
      - api
    command: npm run start
    env_file:
      - .env
